code snippet and new components added
aitsis/ait-ui pull request #22
Opened 2023-07-06 21:57 UTC by SemihArslanhw

2023-07-08 07:10 UTC, hozgur reviewed
Ben bunun ne olduğunu anlamadım.

2023-07-08 07:12 UTC, hozgur commented on ait_ui/components/accordion.py
> +     isAccordionOpen = True
bu hatalı. sonraki if kullanımını anlamsız kılıyot.

2023-07-08 07:15 UTC, hozgur reviewed
Yorumlar ekledim

2023-07-08 07:15 UTC, hozgur commented on examples/imaginer.py
> +from ait_ui.components.accordion import Accordion
niye üsttekilerden farklı

2023-07-08 07:15 UTC, hozgur commented on examples/imaginer.py
Bu örnek kod gereksiz karışık. Çok sade olamlı ki hem kontrol edilebilsin hem de bir kullanıcı anlayabilsin.

2023-07-08 08:56 UTC, SemihArslanhw commented
> Ben bunun ne olduğunu anlamadım.

Abi vs-code snippet e bir prefix ve bu prefixin karşılığında bize ne dondurucegini veriyoruz , yani bir dosyaya girip from yazdığımızda bize  direkt snippet olarak bütün from ile başlayan prefixleri gösteriyor sonra aralarından seçtiğimiz prefixin bodysini yazdiriyor

2023-07-10 10:38 UTC, hozgur requested changes
Imaginer.py silinmiş

2023-07-10 10:42 UTC, hozgur approved these changes
ok

2023-07-10 10:44 UTC, merged